import Head from "next/head";
import { Box, HStack, SimpleGrid } from "@chakra-ui/react";
import Header from "../components/Header";
import Banner from "../components/Banner";
import { SmallCardProps, MediumCardProps } from "../modal/CardProps";
import React from "react";
import SmallCard from "../components/SmallCard";
import Section from "../components/Section";
import MediumCard from "../components/MediumCard";
import LargeCard from "../components/LargeCard";
import Footer from "../components/Footer";

export default function Home({
  exploreData,
  liveAnywhereData,
}: {
  exploreData: SmallCardProps[];
  liveAnywhereData: MediumCardProps[];
}) {
  return (
    <Box>
      <Head>
        <title>Airbnb</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />
      <Banner />

      <Box maxW="1200px" margin="auto" px={6}>
        <Section heading="Explore Nearby">
          <SimpleGrid columns={[1, 2, 2, 4]} spacing={4}>
            {exploreData?.map((destination) => {
              return (
                <SmallCard
                  img={destination.img}
                  location={destination.location}
                  distance={destination.distance}
                  key={`small-card-${destination.location}`}
                />
              );
            })}
          </SimpleGrid>
        </Section>
        <Section heading="Live Anywhere">
          <HStack
            sx={{
              "&::-webkit-scrollbar": {
                display: "none",
              },
            }}
            overflowX="scroll"
            overflowY="hidden"
            spacing={4}
            ml={-2}
          >
            {liveAnywhereData?.map((destination) => {
              return (
                <MediumCard
                  img={destination.img}
                  title={destination.title}
                  key={`medium-card-${destination.title}`}
                />
              );
            })}
          </HStack>
        </Section>
        <LargeCard />
      </Box>
      <Footer />
    </Box>
  );
}

export async function getStaticProps() {
  const exploreData = await fetch("https://links.papareact.com/pyp").then(
    (res) => res.json()
  );

  const liveAnywhereData = await fetch("https://links.papareact.com/zp1").then(
    (res) => res.json()
  );

  return {
    props: {
      exploreData,
      liveAnywhereData,
    },
  };
}
