import Head from "next/head";
import { Box, Heading } from "@chakra-ui/react";
import Header from "../components/Header";

export default function Home() {
  return (
    <Box>
      <Head>
        <title>Airbnb</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      {/* Banner */}
    </Box>
  );
}
