import Head from "next/head";
import {
  Box,
  Button,
  Heading,
  HStack,
  SimpleGrid,
  Text,
} from "@chakra-ui/react";
import Header from "../components/Header";
import Banner from "../components/Banner";
import { DestinationModal } from "../modal/Destination";
import React from "react";
import SmallCard from "../components/SmallCard";
import Section from "../components/Section";
import MediumCard from "../components/MediumCard";
import Image from "next/image";

export default function Home({
  exploreData,
  liveAnywhereData,
}: {
  exploreData: DestinationModal[];
  liveAnywhereData: DestinationModal[];
}) {
  return (
    <Box>
      <Head>
        <title>Airbnb</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />
      <Banner />

      <Box maxW="1200px" margin="auto" px={6}>
        <Section heading="Explore Nearby">
          <SimpleGrid columns={[1, 2, 2, 4]} spacing={4}>
            {exploreData?.map((destination) => {
              return (
                <SmallCard
                  destination={destination}
                  key={`small-card-${destination.location}`}
                />
              );
            })}
          </SimpleGrid>
        </Section>
        <Section heading="Live Anywhere">
          <HStack
            sx={{
              "&::-webkit-scrollbar": {
                display: "none",
              },
            }}
            overflowX="scroll"
            overflowY="hidden"
            spacing={4}
            ml={-2}
          >
            {liveAnywhereData?.map((destination) => {
              return (
                <MediumCard
                  destination={destination}
                  key={`medium-card-${destination.title}`}
                />
              );
            })}
          </HStack>
        </Section>
        <Box
          my={12}
          w="100%"
          h="360px"
          position="relative"
          borderRadius="xl"
          overflow="hidden"
        >
          <Image
            src="https://links.papareact.com/4cj"
            layout="fill"
            objectFit="cover"
          />
          <Box position="absolute" top="10%" left="10%">
            <Heading as="h3">The Greatest Outdoors</Heading>
            <Text>Wishlist curated by Airbnb.</Text>
            <Button>Get Insprired</Button>
          </Box>
        </Box>
      </Box>
    </Box>
  );
}

export async function getStaticProps() {
  const exploreData = await fetch("https://links.papareact.com/pyp").then(
    (res) => res.json()
  );

  const liveAnywhereData = await fetch("https://links.papareact.com/zp1").then(
    (res) => res.json()
  );

  return {
    props: {
      exploreData,
      liveAnywhereData,
    },
  };
}
